export type FAQ = { question: string; answer: string };

export const faqs: FAQ[] = [
  { question: "What is a fractional COO?", answer: "A fractional COO is a senior operating leader who works with a company on an ongoing, part-time basis. Rather than providing a one-time recommendation, a fractional COO helps lead the operating system: priorities, leadership cadence, accountability, decisions, and execution. It gives a growing business access to COO-level leadership before a full-time role is justified." },
  { question: "What is a fractional Integrator?", answer: "An Integrator is an operating counterpart to a founder or Visionary. The role connects the company's direction to coordinated work across leaders and functions: clarifying ownership, facilitating decisions, resolving issues, and following through on priorities. The term is associated with EOS, but the practical role can be useful outside EOS as well." },
  { question: "What is the difference between a fractional COO and a consultant?", answer: "A consultant typically studies a defined problem and recommends what to change. A fractional COO joins the ongoing operating rhythm and helps the team make the change happen—often by leading meetings, coordinating priorities, strengthening accountability, and working through execution issues. The difference is continued operating ownership, not just advice." },
  { question: "How do I know whether I need a COO?", answer: "A COO or Integrator may be timely when customers and headcount are growing, a leadership team is in place, and execution still routes through the founder. Look for repeated escalations, stalled cross-functional work, unclear ownership, priorities that slip, and meetings that do not resolve issues. The right role depends on the work that is not being owned today." },
  { question: "What size company is a good fit?", answer: "The strongest starting point is usually a founder-led company with roughly 10–75 employees, customers, and an emerging leadership layer. Headcount is only a guide. Operating complexity, the founder's role, and whether the company is ready to share ownership matter more than a specific revenue or employee threshold." },
  { question: "Do you only work with companies running EOS?", answer: "No. Martin can work with companies that use EOS, an EOS-like approach, or another management system. Useful practices such as a leadership cadence, scorecards, quarterly priorities, and issue resolution can be adapted without requiring a formal system or implying an EOS affiliation." },
  { question: "How much time do you spend inside the business?", answer: "The level of involvement depends on company complexity, leadership needs, and the priorities Martin is asked to own. Engagements are recurring retainers with enough continuity to influence how the business operates; they are not hourly task coverage. Weekly cadence and availability are defined together before work begins." },
  { question: "Do you manage employees directly?", answer: "The engagement is designed around the agreed operating role. Martin works directly with the founder and leaders on accountability, decisions, coordination, and management routines. Whether that includes direct supervision or formal personnel responsibility should be explicitly agreed with the company rather than assumed." },
  { question: "How long do engagements usually last?", answer: "Operational change needs continuity: leaders have to practice the new cadence, owners need to build follow-through, and processes need to work in real conditions. Engagement length is based on the company's objectives and internal capability. The aim is stronger internal ownership over time, not dependence on an outside operator indefinitely." },
  { question: "Can you help us hire a full-time COO?", answer: "Yes, if a permanent operating leader is the right next step. A fractional engagement can clarify the actual remit, decision rights, and leadership needs before recruiting. Martin can help the founder define the role and prepare the organization for a handoff; recruiting support and scope should be discussed directly." },
  { question: "Can you work with our existing leadership team?", answer: "Yes. Fractional operational leadership should make the existing leadership team more effective, not bypass it. The work clarifies how leaders share priorities, surface issues, make decisions, and hold one another accountable while respecting the company's existing roles and strengths." },
  { question: "What happens during the first 90 days?", answer: "Work begins by understanding how decisions, work, and accountability actually move. Martin reviews the leadership cadence, priorities, scorecards, roles, and important workflows with the founder and team. Together, you align on the few operating changes that matter most, install or improve the routines, and begin running them in the business. The exact sequence is set after an initial assessment." },
  { question: "Do you work remotely or on-site?", answer: "Remote work is available, and on-site involvement can be discussed based on the team's location and the needs of the engagement. The right mix depends on leadership routines, operational context, and what will help the team work together effectively." },
  { question: "Do you work outside Atlanta?", answer: "Martin Operational Strategy is based around Atlanta and Georgia, with remote engagements available beyond the immediate region. Travel and on-site expectations are agreed based on the company and engagement." },
  { question: "How are engagements priced?", answer: "Most engagements begin with an operational assessment and continue as an ongoing fractional leadership retainer. Scope reflects the company's complexity, the leadership responsibilities involved, and the expected weekly participation. The conversation is about a defined operating role and continuity—not buying a block of freelance hours." },
  { question: "What if we already have an operations manager?", answer: "An operations manager and a fractional COO can complement one another. The manager may own daily process execution while a COO-level operator works with the founder and leadership team on priorities, cross-functional coordination, accountability, and management capability. The first step is to understand where ownership currently breaks down." },
  { question: "What is the difference between an Integrator and an operations manager?", answer: "An operations manager usually owns a defined team, function, or set of processes. An Integrator is typically a senior company-wide operating counterpart to the founder, coordinating leadership priorities across functions and helping the organization execute as a whole. Company size and role design can change the boundary, so decision rights need to be explicit." },
  { question: "What if the company is not ready for a full operating-system overhaul?", answer: "The work should match the business, not impose process for its own sake. It can begin with a small number of changes—such as clarifying meeting ownership, tracking a few meaningful measures, or assigning owners to stalled priorities—and expand only when those routines help the team execute." },
];
