import type { Metadata } from "next";
import Link from "next/link";
import { CTA } from "@/components/cta";
import { JsonLd } from "@/components/json-ld";
import { breadcrumbSchema, personSchema } from "@/lib/structured-data";
import { operatorName, pageMetadata } from "@/lib/site";

export const metadata: Metadata = pageMetadata("About Jeff Martin | Fractional COO & Integrator", "Meet Jeff Martin and learn how Martin Operational Strategy works with founders and leadership teams to strengthen accountability and execution.", "/about");

export default function AboutPage() {
  return <>
    <JsonLd data={personSchema()} /><JsonLd data={breadcrumbSchema([{ name: "Home", path: "/" }, { name: "About", path: "/about" }])} />
    <section className="page-hero"><div className="container"><span className="eyebrow">About the operator</span><h1>Jeff Martin works on the operating side of the business.</h1><p>Martin Operational Strategy exists for founders who have customers, people, and momentum—and need an experienced operator to help the company execute without routing every decision through them.</p></div></section>
    <section className="section section--dark"><div className="container service-split"><div><span className="eyebrow">Operator, not observer</span><h2 style={{ marginTop: "1rem" }}>The job is to help the team run the work.</h2></div><div className="content-stack"><p style={{ fontSize: "1.1rem" }}>Jeff works directly with the founder and leadership team in the operating rhythm of the company. The work is practical: make ownership visible, keep priorities moving, resolve issues at the right level, and strengthen the routines leaders use every week.</p><p>That means listening to how work actually gets done, not imposing process for its own sake. It means being candid about trade-offs, creating enough structure to make commitments real, and helping managers take on more of the operating responsibility.</p><p>The work is grounded in the company’s actual operating needs: leadership cadence, accountable owners, practical measures, manager capability, and useful working relationships between the founder and team.</p></div></div></section>
    <section className="section"><div className="container"><div className="section-heading"><span className="eyebrow">How Jeff works</span><h2>Calm structure, close to the real work.</h2></div><div className="comparison"><article><span className="eyebrow">With founders</span><h3>Make room for higher-leverage work</h3><p>Identify the decisions and coordination work that should no longer depend on the founder, then establish how the team will own them.</p></article><article><span className="eyebrow">With leaders</span><h3>Make accountability workable</h3><p>Clarify what each leader owns, create a shared operating cadence, and help resolve the issues that cross team boundaries.</p></article><article><span className="eyebrow">With managers</span><h3>Build confidence and follow-through</h3><p>Support managers with clear expectations, decision paths, practical measures, and routines that make progress visible.</p></article></div></div></section>
    <section className="section section--sage"><div className="container service-split"><div><span className="eyebrow">Operating philosophy</span><h2 style={{ marginTop: "1rem" }}>Good operations create leverage, not bureaucracy.</h2></div><div className="content-stack"><p>Structure should answer practical questions: What matters now? Who owns it? How will we know if it is off track? Where should a decision be made? How will the team resolve the issue?</p><p>When those answers are clear, leaders spend less time interpreting priorities and the founder does not have to act as the company’s memory, coordinator, and escalation path. The aim is a more capable business—not a more complicated one.</p><Link className="text-link" href="/services/fractional-integrator">Learn about the Integrator role</Link></div></div></section>
    <CTA title={`A little more about ${operatorName}. A lot more about how your business can run.`} body="Use an Operations Fit Call to share what's landing on your desk and talk through whether an embedded operator is the right fit." />
  </>;
}
