import Link from "next/link";
import { CTA } from "@/components/cta";
import { JsonLd } from "@/components/json-ld";
import { SectionHeading } from "@/components/section-heading";
import type { ServicePageContent } from "@/content/services";
import { breadcrumbSchema, serviceSchema } from "@/lib/structured-data";
import { bookingUrl } from "@/lib/site";

export function ServicePage({ service }: { service: ServicePageContent }) {
  return <>
    <JsonLd data={serviceSchema(service.eyebrow, service.description, service.path)} />
    <JsonLd data={breadcrumbSchema([{ name: "Home", path: "/" }, { name: "Services", path: "/services/fractional-coo" }, { name: service.eyebrow, path: service.path }])} />
    <section className="page-hero"><div className="container"><span className="eyebrow">{service.eyebrow} · Atlanta, Georgia + remote</span><h1>{service.headline}</h1><p>{service.intro}</p><div className="hero-actions"><Link className="button" href={bookingUrl} data-analytics-event="fit_call_click" data-analytics-location="service_hero">Book an Operations Fit Call <span aria-hidden="true">↗</span></Link><Link className="button button--outline" href="/process">See the engagement model</Link></div></div></section>
    <section className="section section--dark"><div className="container service-split"><div><span className="eyebrow">When this helps</span><h2 style={{ marginTop: "1rem", fontSize: "clamp(2.4rem, 4.7vw, 4rem)" }}>A leadership need that has outgrown founder bandwidth.</h2></div><div className="content-stack"><p style={{ fontSize: "1.1rem" }}>A fractional operator is most useful when the business has already found customers and is growing—but its operating system has not kept pace. More effort from the founder is no longer the best answer.</p><ul className="check-list">{service.bestFor.map((item) => <li key={item}>{item}</li>)}</ul></div></div></section>
    <section className="section"><div className="container service-split"><aside className="service-aside"><span>Scope / what the operator owns</span><p>Exact involvement is shaped around complexity, leadership needs, and the work that has to move now.</p><Link className="text-link" href="/contact">Talk through the fit</Link></aside><div className="content-stack"><div><span className="eyebrow">A role inside the operating rhythm</span><h2 style={{ marginTop: "1rem" }}>What Martin helps own</h2><p>The specific remit is agreed with the founder and leadership team. Common areas of ownership include:</p><ul className="check-list">{service.owns.map((item) => <li key={item}>{item}</li>)}</ul></div><div><h2>{service.distinctionTitle}</h2><p>{service.distinction}</p></div></div></div></section>
    <section className="section section--sage"><div className="container"><SectionHeading eyebrow="What changes" title="A stronger operating layer creates leverage for the whole leadership team." body="The measure is not how many processes get written. It is whether people can see what matters, know what they own, and act without unnecessary escalation."/><div className="fit-checks">{service.outcomes.map((item) => <div className="fit-check" key={item}>{item}</div>)}</div><div style={{ marginTop: "2.5rem" }}><Link className="text-link" href="/process">Explore the first 90 days</Link></div></div></section>
    <section className="section"><div className="container"><SectionHeading eyebrow="A related role" title="The right operating role depends on what the business needs."/><div className="link-grid"><Link className="link-card" href={service.path.includes("coo") ? "/services/fractional-integrator" : "/services/fractional-coo"}><div><h3>{service.path.includes("coo") ? "Fractional Integrator" : "Fractional COO"}</h3><p>{service.path.includes("coo") ? "A founder's operating counterpart, focused on translating direction into aligned execution." : "Broader senior responsibility for the company's operating performance and leadership system."}</p></div><span className="text-link">Compare the role</span></Link><Link className="link-card" href="/case-studies"><div><h3>How the work is structured</h3><p>Understand the diagnose, align, install, run, and transfer sequence.</p></div><span className="text-link">See how we work</span></Link></div></div></section>
    <CTA />
  </>;
}
