import type { Metadata } from "next";
import Link from "next/link";
import { CTA } from "@/components/cta";
import { SectionHeading } from "@/components/section-heading";
import { JsonLd } from "@/components/json-ld";
import { breadcrumbSchema } from "@/lib/structured-data";
import { pageMetadata } from "@/lib/site";

export const metadata: Metadata = pageMetadata("How We Work: The First 90 Days with a Fractional COO", "See how a fractional COO engagement moves from operating assessment to leadership alignment, installed routines, active execution, and stronger internal ownership.", "/process");
const phases = [
  { title: "Diagnose", span: "Understand the real operating picture", detail: "Start with the founder and leadership team. Review how work moves across the company: meeting cadence, priorities, decision ownership, scorecards, roles, and critical workflows. The goal is to find the constraints that matter—not to audit everything.", output: "Output: an operational baseline and a prioritized 90-day plan." },
  { title: "Align", span: "Agree on what changes first", detail: "Clarify the outcomes leaders are responsible for, who owns which decisions, and what the company will focus on. Surface misalignment early so the team can make explicit commitments instead of carrying different assumptions.", output: "Output: a clear operating model and shared leadership priorities." },
  { title: "Install", span: "Put useful operating routines in place", detail: "Implement or improve the leadership meeting, scorecard, priority review, issue-resolution process, and the few workflows most connected to execution. Keep each routine simple enough that leaders will use it when the work gets busy.", output: "Output: a functioning execution system the team can practice." },
  { title: "Run", span: "Work inside the operating rhythm", detail: "Martin participates in agreed leadership routines, tracks follow-through, helps resolve executive-level issues, coordinates work across functions, and supports managers in keeping their commitments visible.", output: "Output: more predictable execution and fewer avoidable founder escalations." },
  { title: "Transfer / scale", span: "Build durable internal ownership", detail: "As the team gains confidence, strengthen internal leaders, document core operating routines, and adjust Martin's involvement. If the company needs a permanent COO or Integrator, prepare the remit and handoff around the work the business actually needs.", output: "Output: stronger internal capability and a thoughtful next operating model." },
];

export default function ProcessPage() {
  return <>
    <JsonLd data={breadcrumbSchema([{ name: "Home", path: "/" }, { name: "How We Work", path: "/process" }])} />
    <section className="page-hero"><div className="container"><span className="eyebrow">How we work · A practical sequence</span><h1>First understand the friction. Then help the team run better.</h1><p>An operating engagement is not a fixed playbook or a diagnostic that ends with a presentation. It is a path from a clear baseline to routines and accountability the leadership team can use.</p><div className="hero-actions"><Link className="button" href="/contact">Discuss your operating needs <span aria-hidden="true">↗</span></Link></div></div></section>
    <section className="section"><div className="container"><SectionHeading eyebrow="The engagement" title="Five stages, shaped around the business—not a consulting binder." body="A clear start builds shared context. Embedded work makes the changes real. Transfer keeps progress from depending on one outside person."/><div className="phase-list">{phases.map((phase, index) => <article className="phase" key={phase.title}><span className="phase-number">0{index + 1} / 05</span><div><h3>{phase.title}</h3><p className="muted">{phase.span}</p></div><div><p>{phase.detail}</p><small>{phase.output}</small></div></article>)}</div></div></section>
    <section className="section section--sage"><div className="container service-split"><div><span className="eyebrow">Commercial model</span><h2 style={{ marginTop: "1rem" }}>Continuity matters more than hours.</h2></div><div className="content-stack"><p>Most engagements begin with an operational assessment, followed by an ongoing fractional leadership retainer. Scope depends on operating complexity, the responsibilities Martin owns, and the weekly involvement required to create real change.</p><p>This is not hourly task work. It needs enough continuity to establish routines, work through issues as they arise, and help leaders take ownership. The assessment and fit conversation clarify what level makes sense.</p><Link className="text-link" href="/operations-assessment">Explore the operations assessment</Link></div></div></section>
    <section className="section"><div className="container"><SectionHeading eyebrow="What you can expect" title="No generic transformation program."/><div className="comparison"><article><span className="eyebrow">Start with reality</span><h3>Work as it happens</h3><p>Understand real handoffs, decisions, and meetings—not just the org chart and process documents.</p></article><article><span className="eyebrow">Keep it useful</span><h3>Make the work visible</h3><p>Focus on clear ownership, a few meaningful measures, and the priorities the team needs to move.</p></article><article><span className="eyebrow">Build capability</span><h3>Strengthen the team</h3><p>Help leaders run the operating system themselves as the company’s needs and internal capacity evolve.</p></article></div></div></section>
    <CTA />
  </>;
}
