import type { Metadata } from "next";
import Link from "next/link";
import { CTA } from "@/components/cta";
import { JsonLd } from "@/components/json-ld";
import { breadcrumbSchema, serviceSchema } from "@/lib/structured-data";
import { pageMetadata } from "@/lib/site";

const description = "Fractional COO and Integrator services for founder-led businesses in Atlanta and across Georgia. Embedded operating leadership, with remote engagements available.";
export const metadata: Metadata = pageMetadata("Fractional COO in Atlanta, Georgia", description, "/atlanta-fractional-coo");

export default function AtlantaPage() {
  return <>
    <JsonLd data={serviceSchema("Fractional COO and Integrator services in Atlanta, Georgia", description, "/atlanta-fractional-coo")} />
    <JsonLd data={breadcrumbSchema([{ name: "Home", path: "/" }, { name: "Atlanta Fractional COO", path: "/atlanta-fractional-coo" }])} />
    <section className="page-hero"><div className="container"><span className="eyebrow">Atlanta · Georgia · Remote</span><h1>Fractional COO leadership for Atlanta founder-led businesses.</h1><p>Martin Operational Strategy works with growing Atlanta-area companies that have outgrown founder-led operations. Bring in an experienced operator to strengthen leadership accountability, clarify ownership, and help the business execute without routing every decision through the founder.</p><div className="hero-actions"><Link className="button" href="/contact">Request an Operations Fit Call <span aria-hidden="true">↗</span></Link></div></div></section>
    <section className="section section--dark"><div className="container service-split"><div><span className="eyebrow">Local fit, practical work</span><h2 style={{ marginTop: "1rem" }}>Built around how your business actually operates.</h2></div><div className="content-stack"><p>Founder-led service and operational businesses grow through people, handoffs, and customer commitments. As the business adds teams and managers, coordination can become a second job for the founder. A fractional COO or Integrator helps build a stronger operating layer for that complexity.</p><p>Engagements can be remote or include on-site work when the operating context calls for it. The right arrangement depends on leadership routines, the company’s location, and the work the operator is expected to own. Location alone does not determine fit.</p></div></div></section>
    <section className="section"><div className="container"><div className="section-heading"><span className="eyebrow">Atlanta fractional operations support</span><h2>Senior operating leadership—without assuming a full-time hire is next.</h2><p>The work is most useful when customer demand is established and execution has become the constraint. The goal is clearer ownership and a more reliable operating cadence, not more process for its own sake.</p></div><div className="link-grid"><Link className="link-card" href="/services/fractional-coo"><div><h3>Fractional COO</h3><p>Senior operational leadership focused on company-wide execution.</p></div><span className="text-link">Explore fractional COO services</span></Link><Link className="link-card" href="/services/fractional-integrator"><div><h3>Fractional Integrator</h3><p>A founder’s operating counterpart, explained in plain English.</p></div><span className="text-link">Explore Integrator services</span></Link></div></div></section>
    <section className="section section--sage"><div className="container service-split"><div><span className="eyebrow">Who we work with</span><h2 style={{ marginTop: "1rem" }}>Established businesses with a leadership layer.</h2></div><div className="content-stack"><p>A common fit is an Atlanta or Georgia founder-led service business with a growing team, managers, and important priorities that are hard to execute consistently. The founder may still be the default decision-maker, project coordinator, or keeper of the company’s commitments.</p><p>Company size and revenue are guides, not admission rules. The more useful question is whether the company has enough traction to benefit from stronger operational leadership and is willing to build ownership beyond the founder.</p><Link className="text-link" href="/operations-assessment">Review founder dependency and operating maturity</Link></div></div></section>
    <CTA title="Looking for a fractional COO in Atlanta?" body="Describe the operational challenge and where the business is based. We’ll discuss the engagement context and whether the role is a fit." />
  </>;
}
